import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import pdb; pdb.set_trace()

# Read the text file into a DataFrame
cora_pnode_imex_1bee = pd.read_csv('./Cora_pnode_mytransformer_imex_1bee.txt', delimiter=',',header=None)
cora_pnode_imex_a2 = pd.read_csv('./Cora_pnode_mytransformer_imex_a2.txt', delimiter=',',header=None)
cora_pnode_imex_l2 = pd.read_csv('./Cora_pnode_mytransformer_imex_l2.txt', delimiter=',',header=None)
cora_pnode_imex_ars122 = pd.read_csv('./Cora_pnode_mytransformer_imex_ars122.txt', delimiter=',',header=None)
cora_pnode_imex_3 = pd.read_csv('./Cora_pnode_mytransformer_imex_3.txt', delimiter=',',header=None)
cora_pnode_imex_bpr3 = pd.read_csv('./Cora_pnode_mytransformer_imex_bpr3.txt', delimiter=',',header=None)
cora_pnode_imex_ars443 = pd.read_csv('./Cora_pnode_mytransformer_imex_ars443.txt', delimiter=',',header=None)
cora_pnode_imex_4 = pd.read_csv('./Cora_pnode_mytransformer_imex_4.txt', delimiter=',',header=None)
cora_pnode_imex_5 = pd.read_csv('./Cora_pnode_mytransformer_imex_5.txt', delimiter=',',header=None)
cora_nl_implicit_adams = pd.read_csv('./Cora_constant_transformer_implicit_adams.txt', delimiter=',',header=None)

coau_pnode_imex_1bee = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex_1bee.txt', delimiter=',',header=None)
coau_pnode_imex_a2 = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex_a2.txt', delimiter=',',header=None)
coau_pnode_imex_l2 = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex_l2.txt', delimiter=',',header=None)
coau_pnode_imex_ars122 = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex_ars122.txt', delimiter=',',header=None)
coau_pnode_imex_3 = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex_3.txt', delimiter=',',header=None)
coau_pnode_imex_bpr3 = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex_bpr3.txt', delimiter=',',header=None)
coau_pnode_imex_ars443 = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex_ars443.txt', delimiter=',',header=None)
coau_pnode_imex_4 = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex_4.txt', delimiter=',',header=None)
coau_pnode_imex_5 = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex_5.txt', delimiter=',',header=None)
coau_nl_implicit_adams = pd.read_csv('./CoauthorCS_constant_transformer_implicit_adams.txt', delimiter=',',header=None)

photo_pnode_imex_1bee = pd.read_csv('./Photo_pnode_mytransformer_imex_1bee.txt', delimiter=',',header=None)
photo_pnode_imex_a2 = pd.read_csv('./Photo_pnode_mytransformer_imex_a2.txt', delimiter=',',header=None)
photo_pnode_imex_l2 = pd.read_csv('./Photo_pnode_mytransformer_imex_l2.txt', delimiter=',',header=None)
photo_pnode_imex_ars122 = pd.read_csv('./Photo_pnode_mytransformer_imex_ars122.txt', delimiter=',',header=None)
photo_pnode_imex_3 = pd.read_csv('./Photo_pnode_mytransformer_imex_3.txt', delimiter=',',header=None)
photo_pnode_imex_bpr3 = pd.read_csv('./Photo_pnode_mytransformer_imex_bpr3.txt', delimiter=',',header=None)
photo_pnode_imex_ars443 = pd.read_csv('./Photo_pnode_mytransformer_imex_ars443.txt', delimiter=',',header=None)
photo_pnode_imex_4 = pd.read_csv('./Photo_pnode_mytransformer_imex_4.txt', delimiter=',',header=None)
photo_pnode_imex_5 = pd.read_csv('./Photo_pnode_mytransformer_imex_5.txt', delimiter=',',header=None)
photo_nl_implicit_adams = pd.read_csv('./Photo_constant_transformer_implicit_adams.txt', delimiter=',',header=None)


fig, (ax1, ax2, ax3) = plt.subplots(1, 3)
# make a little extra space between the subplots
fig.subplots_adjust(hspace=0.33)

ax1.plot(np.cumsum(cora_pnode_imex_1bee.iloc[:, 1]), 100 *  cora_pnode_imex_1bee.iloc[:, 7], label='pnode_imex_1bee', color='blue')
ax1.plot(np.cumsum(cora_pnode_imex_a2.iloc[:, 1]), 100 *  cora_pnode_imex_a2.iloc[:, 7], label='pnode_imex_a2', color='black')
ax1.plot(np.cumsum(cora_pnode_imex_l2.iloc[:, 1]), 100 *  cora_pnode_imex_l2.iloc[:, 7], label='pnode_imex_l2', color='red')
ax1.plot(np.cumsum(cora_pnode_imex_ars122.iloc[:, 1]), 100 *  cora_pnode_imex_ars122.iloc[:, 7], label='pnode_imex_ars122', color='cyan')
#ax1.plot(np.cumsum(cora_pnode_imex_3.iloc[:, 1]), 100 *  cora_pnode_imex_3.iloc[:, 7], label='pnode_imex_3', color='pink')
#ax1.plot(np.cumsum(cora_pnode_imex_bpr3.iloc[:, 1]), 100 *  cora_pnode_imex_bpr3.iloc[:, 7], label='pnode_imex_bpr3', color='yellow')
#ax1.plot(np.cumsum(cora_pnode_imex_ars443.iloc[:, 1]), 100 *  cora_pnode_imex_ars443.iloc[:, 7], label='pnode_imex_ars443', color='orange')
#ax1.plot(np.cumsum(cora_pnode_imex_4.iloc[:, 1]), 100 *  cora_pnode_imex_4.iloc[:, 7], label='pnode_imex_4', color='brown')
#ax1.plot(np.cumsum(cora_pnode_imex_5.iloc[:, 1]), 100 *  cora_pnode_imex_5.iloc[:, 7], label='pnode_imex_5', color='green')
ax1.plot(np.cumsum(cora_nl_implicit_adams.iloc[:, 1]), 100 *  cora_nl_implicit_adams.iloc[:, 7], label='nl_implicit_adams', color='purple')
ax1.set_xscale('log')
ax1.set_xlabel('Clock Time')
ax1.set_ylabel('Testing Accuracy (%)')
ax1.legend()
ax1.title.set_text('Cora')

ax2.plot(np.cumsum(coau_pnode_imex_1bee.iloc[:, 1]), 100 *  coau_pnode_imex_1bee.iloc[:, 7], label='pnode_imex_1bee', color='blue')
ax2.plot(np.cumsum(coau_pnode_imex_a2.iloc[:, 1]), 100 *  coau_pnode_imex_a2.iloc[:, 7], label='pnode_imex_a2', color='black')
ax2.plot(np.cumsum(coau_pnode_imex_l2.iloc[:, 1]), 100 *  coau_pnode_imex_l2.iloc[:, 7], label='pnode_imex_l2', color='red')
ax2.plot(np.cumsum(coau_pnode_imex_ars122.iloc[:, 1]), 100 *  coau_pnode_imex_ars122.iloc[:, 7], label='pnode_imex_ars122', color='cyan')
#ax2.plot(np.cumsum(coau_pnode_imex_3.iloc[:, 1]), 100 *  coau_pnode_imex_3.iloc[:, 7], label='pnode_imex_3', color='pink')
#ax2.plot(np.cumsum(coau_pnode_imex_bpr3.iloc[:, 1]), 100 *  coau_pnode_imex_bpr3.iloc[:, 7], label='pnode_imex_bpr3', color='yellow')
#ax2.plot(np.cumsum(coau_pnode_imex_ars443.iloc[:, 1]), 100 *  coau_pnode_imex_ars443.iloc[:, 7], label='pnode_imex_ars443', color='orange')
#ax2.plot(np.cumsum(coau_pnode_imex_4.iloc[:, 1]), 100 *  coau_pnode_imex_4.iloc[:, 7], label='pnode_imex_4', color='brown')
#ax2.plot(np.cumsum(coau_pnode_imex_5.iloc[:, 1]), 100 *  coau_pnode_imex_5.iloc[:, 7], label='pnode_imex_5', color='green')
ax2.plot(np.cumsum(coau_nl_implicit_adams.iloc[:, 1]), 100 *  coau_nl_implicit_adams.iloc[:, 7], label='nl_implicit_adams', color='purple')
ax2.set_xscale('log')
ax2.set_xlabel('Clock Time')
ax2.set_ylabel('Testing Accuracy (%)')
ax2.legend()
ax2.title.set_text('CoauthorCS')

ax3.plot(np.cumsum(photo_pnode_imex_1bee.iloc[:, 1]), 100 * photo_pnode_imex_1bee.iloc[:, 7], label='pnode_imex_1bee', color='blue')
ax3.plot(np.cumsum(photo_pnode_imex_a2.iloc[:, 1]), 100 * photo_pnode_imex_a2.iloc[:, 7], label='pnode_imex_a2', color='black')
ax3.plot(np.cumsum(photo_pnode_imex_l2.iloc[:, 1]), 100 * photo_pnode_imex_l2.iloc[:, 7], label='pnode_imex_l2', color='red')
ax3.plot(np.cumsum(photo_pnode_imex_ars122.iloc[:, 1]), 100 * photo_pnode_imex_ars122.iloc[:, 7], label='pnode_imex_ars122', color='cyan')
#ax3.plot(np.cumsum(photo_pnode_imex_3.iloc[:, 1]), 100 * photo_pnode_imex_3.iloc[:, 7], label='pnode_imex_3', color='pink')
#ax3.plot(np.cumsum(photo_pnode_imex_bpr3.iloc[:, 1]), 100 * photo_pnode_imex_bpr3.iloc[:, 7], label='pnode_imex_bpr3', color='yellow')
#ax3.plot(np.cumsum(photo_pnode_imex_ars443.iloc[:, 1]), 100 * photo_pnode_imex_ars443.iloc[:, 7], label='pnode_imex_ars443', color='orange')
#ax3.plot(np.cumsum(photo_pnode_imex_4.iloc[:, 1]), 100 * photo_pnode_imex_4.iloc[:, 7], label='pnode_imex_4', color='brown')
#ax3.plot(np.cumsum(photo_pnode_imex_5.iloc[:, 1]), 100 * photo_pnode_imex_5.iloc[:, 7], label='pnode_imex_5', color='green')
ax3.plot(np.cumsum(photo_nl_implicit_adams.iloc[:, 1]), 100 *  photo_nl_implicit_adams.iloc[:, 7], label='nl_implicit_adams', color='purple')
ax3.set_xscale('log')
ax3.set_xlabel('Clock Time')
ax3.set_ylabel('Testing Accuracy (%)')
ax3.legend()
ax3.title.set_text('Photo')

#fig.suptitle('')
plt.show()