import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import pdb; pdb.set_trace()

# Read the text file into a DataFrame
cora_l_dopri5 = pd.read_csv('./Cora_attention_laplacian_dopri5.txt', delimiter=',',header=None)
cora_l_dopri8 = pd.read_csv('./Cora_attention_laplacian_dopri8.txt', delimiter=',',header=None)
#cora_l_adaptive_heun = pd.read_csv('./Cora_attention_laplacian_adaptive_heun.txt', delimiter=',',header=None)
cora_l_implicit_adams = pd.read_csv('./Cora_attention_laplacian_implicit_adams.txt', delimiter=',',header=None)
cora_nl_dopri5 = pd.read_csv('./Cora_constant_transformer_dopri5.txt', delimiter=',',header=None)
cora_nl_dopri8 = pd.read_csv('./Cora_constant_transformer_dopri8.txt', delimiter=',',header=None)
#cora_nl_adaptive_heun = pd.read_csv('./Cora_constant_transformer_adaptive_heun.txt', delimiter=',',header=None)
cora_nl_implicit_adams = pd.read_csv('./Cora_constant_transformer_implicit_adams.txt', delimiter=',',header=None)
cora_pnode_imex = pd.read_csv('./Cora_pnode_mytransformer_imex.txt', delimiter=',',header=None)

coau_l_dopri5 = pd.read_csv('./CoauthorCS_attention_laplacian_dopri5.txt', delimiter=',',header=None)
coau_l_dopri8 = pd.read_csv('./CoauthorCS_attention_laplacian_dopri8.txt', delimiter=',',header=None)
coau_l_adaptive_heun = pd.read_csv('./CoauthorCS_attention_laplacian_adaptive_heun.txt', delimiter=',',header=None)
coau_l_implicit_adams = pd.read_csv('./CoauthorCS_attention_laplacian_implicit_adams.txt', delimiter=',',header=None)
coau_nl_dopri5 = pd.read_csv('./CoauthorCS_constant_transformer_dopri5.txt', delimiter=',',header=None)
coau_nl_dopri8 = pd.read_csv('./CoauthorCS_constant_transformer_dopri8.txt', delimiter=',',header=None)
coau_nl_adaptive_heun = pd.read_csv('./CoauthorCS_constant_transformer_adaptive_heun.txt', delimiter=',',header=None)
coau_nl_implicit_adams = pd.read_csv('./CoauthorCS_constant_transformer_implicit_adams.txt', delimiter=',',header=None)
coau_pnode_imex = pd.read_csv('./CoauthorCS_pnode_mytransformer_imex.txt', delimiter=',',header=None)

photo_l_dopri5 = pd.read_csv('./Photo_attention_laplacian_dopri5.txt', delimiter=',',header=None)
photo_l_dopri8 = pd.read_csv('./Photo_attention_laplacian_dopri8.txt', delimiter=',',header=None)
photo_l_adaptive_heun = pd.read_csv('./Photo_attention_laplacian_adaptive_heun.txt', delimiter=',',header=None)
photo_l_implicit_adams = pd.read_csv('./Photo_attention_laplacian_implicit_adams.txt', delimiter=',',header=None)
photo_nl_dopri5 = pd.read_csv('./Photo_constant_transformer_dopri5.txt', delimiter=',',header=None)
photo_nl_dopri8 = pd.read_csv('./Photo_constant_transformer_dopri8.txt', delimiter=',',header=None)
photo_nl_adaptive_heun = pd.read_csv('./Photo_constant_transformer_adaptive_heun.txt', delimiter=',',header=None)
photo_nl_implicit_adams = pd.read_csv('./Photo_constant_transformer_implicit_adams.txt', delimiter=',',header=None)
photo_pnode_imex = pd.read_csv('./Photo_pnode_mytransformer_imex.txt', delimiter=',',header=None)


fig, (ax1, ax2, ax3) = plt.subplots(1, 3)
# make a little extra space between the subplots
fig.subplots_adjust(hspace=0.33)

ax1.plot(np.cumsum(cora_l_dopri5.iloc[:, 1]), 100 *  cora_l_dopri5.iloc[:, 7], label='l_dopri5', color='blue')
ax1.plot(np.cumsum(cora_l_dopri8.iloc[:, 1]), 100 *  cora_l_dopri8.iloc[:, 7], label='l_dopri8', color='black')
#ax1.plot(np.cumsum(cora_l_adaptive_heun.iloc[:, 1]), 100 *  cora_l_adaptive_heun.iloc[:, 7], label='l_adaptive heun', color='red')
ax1.plot(np.cumsum(cora_l_implicit_adams.iloc[:, 1]), 100 *  cora_l_implicit_adams.iloc[:, 7], label='l_implicit_adams', color='cyan')
ax1.plot(np.cumsum(cora_nl_dopri5.iloc[:, 1]), 100 *  cora_nl_dopri5.iloc[:, 7], label='nl_dopri5', color='pink')
ax1.plot(np.cumsum(cora_nl_dopri8.iloc[:, 1]), 100 *  cora_nl_dopri8.iloc[:, 7], label='nl_dopri8', color='yellow')
#ax1.plot(np.cumsum(cora_nl_adaptive_heun.iloc[:, 1]), 100 *  cora_nl_adaptive_heun.iloc[:, 7], label='nl_adaptive_heun', color='orange')
ax1.plot(np.cumsum(cora_nl_implicit_adams.iloc[:, 1]), 100 *  cora_nl_implicit_adams.iloc[:, 7], label='nl_implicit_adams', color='brown')
ax1.plot(np.cumsum(cora_pnode_imex.iloc[:, 1]), 100 *  cora_pnode_imex.iloc[:, 7], label='pnode_imex', color='green')
#ax1.plot(prox_bdf4.iloc[:, 1]), 100 *  prox_bdf4.iloc[:, 7], label='prox_bdf4', color='purple')
#ax1.set_xlim(1, cora_l_dopri5.iloc[-1, 0])
ax1.set_xscale('log')
ax1.set_xlabel('Clock Time')
ax1.set_ylabel('Testing Accuracy (%)')
ax1.legend()
ax1.title.set_text('Cora')

ax2.plot(np.cumsum(coau_l_dopri5.iloc[:, 1]), 100 *  coau_l_dopri5.iloc[:, 7], label='l_dopri5', color='blue')
ax2.plot(np.cumsum(coau_l_dopri8.iloc[:, 1]), 100 *  coau_l_dopri8.iloc[:, 7], label='l_dopri8', color='black')
ax2.plot(np.cumsum(coau_l_adaptive_heun.iloc[:, 1]), 100 *  coau_l_adaptive_heun.iloc[:, 7], label='l_adaptive heun', color='red')
ax2.plot(np.cumsum(coau_l_implicit_adams.iloc[:, 1]), 100 *  coau_l_implicit_adams.iloc[:, 7], label='l_implicit_adams', color='cyan')
ax2.plot(np.cumsum(coau_nl_dopri5.iloc[:, 1]), 100 *  coau_nl_dopri5.iloc[:, 7], label='nl_dopri5', color='pink')
ax2.plot(np.cumsum(coau_nl_dopri8.iloc[:, 1]), 100 *  coau_nl_dopri8.iloc[:, 7], label='nl_dopri8', color='yellow')
ax2.plot(np.cumsum(coau_nl_adaptive_heun.iloc[:, 1]), 100 *  coau_nl_adaptive_heun.iloc[:, 7], label='nl_adaptive_heun', color='orange')
ax2.plot(np.cumsum(coau_nl_implicit_adams.iloc[:, 1]), 100 *  coau_nl_implicit_adams.iloc[:, 7], label='nl_implicit_adams', color='brown')
ax2.plot(np.cumsum(coau_pnode_imex.iloc[:, 1]), 100 *  coau_pnode_imex.iloc[:, 7], label='pnode_imex', color='green')
#ax2.plot(prox_bdf4.iloc[:, 1]), 100 *  prox_bdf4.iloc[:, 7], label='prox_bdf4', color='purple')
#ax2.set_xlim(1, coau_l_dopri5.iloc[-1, 0])
ax2.set_xscale('log')
ax2.set_xlabel('Clock Time')
ax2.set_ylabel('Testing Accuracy (%)')
ax2.legend()
ax2.title.set_text('CoauthorCS')

ax3.plot(np.cumsum(photo_l_dopri5.iloc[:, 1]), 100 * photo_l_dopri5.iloc[:, 7], label='l_dopri5', color='blue')
ax3.plot(np.cumsum(photo_l_dopri8.iloc[:, 1]), 100 * photo_l_dopri8.iloc[:, 7], label='l_dopri8', color='black')
ax3.plot(np.cumsum(photo_l_adaptive_heun.iloc[:, 1]), 100 * photo_l_adaptive_heun.iloc[:, 7], label='l_adaptive heun', color='red')
ax3.plot(np.cumsum(photo_l_implicit_adams.iloc[:, 1]), 100 * photo_l_implicit_adams.iloc[:, 7], label='l_implicit_adams', color='cyan')
ax3.plot(np.cumsum(photo_nl_dopri5.iloc[:, 1]), 100 * photo_nl_dopri5.iloc[:, 7], label='nl_dopri5', color='pink')
ax3.plot(np.cumsum(photo_nl_dopri8.iloc[:, 1]), 100 * photo_nl_dopri8.iloc[:, 7], label='nl_dopri8', color='yellow')
ax3.plot(np.cumsum(photo_nl_adaptive_heun.iloc[:, 1]), 100 * photo_nl_adaptive_heun.iloc[:, 7], label='nl_adaptive_heun', color='orange')
ax3.plot(np.cumsum(photo_nl_implicit_adams.iloc[:, 1]), 100 * photo_nl_implicit_adams.iloc[:, 7], label='nl_implicit_adams', color='brown')
ax3.plot(np.cumsum(photo_pnode_imex.iloc[:, 1]), 100 * photo_pnode_imex.iloc[:, 7], label='pnode_imex', color='green')
#ax3.plot(prox_bdf4.iloc[:, 1]), 100 * prox_bdf4.iloc[:, 7], label='prox_bdf4', color='purple')
#ax3.set_xlim(1, photo_l_dopri5.iloc[-1, 0])
ax3.set_xscale('log')
ax3.set_xlabel('Clock Time')
ax3.set_ylabel('Testing Accuracy (%)')
ax3.legend()
ax3.title.set_text('Photo')

#fig.suptitle('')
plt.show()